# Generated by Django 2.2.12 on 2024-07-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='startTime',
            new_name='start_time',
        ),
    ]
