# Generated by Django 2.2.12 on 2024-07-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_auto_20240715_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.CharField(max_length=5),
        ),
    ]
