# Generated by Django 3.2.19 on 2024-10-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_shift_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
