# Generated by Django 3.2.19 on 2024-10-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_alter_shift_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='date',
            new_name='shift_date',
        ),
    ]
