[build]
publish = "staticfiles"  # 収集された静的ファイルのディレクトリを指定
command = "python manage.py collectstatic --noinput"  # ビルドコマンドを指定

[context.production.environment]
DJANGO_SETTINGS_MODULE = "shift_scheduler.settings.production"  # プロダクション設定を使用

[context.deploy-preview.environment]
DJANGO_SETTINGS_MODULE = "shift_scheduler.settings.staging"  # ステージング設定を使用

[context.branch-deploy.environment]
DJANGO_SETTINGS_MODULE = "shift_scheduler.settings.staging"  # ステージング設定を使用

[context.dev.environment]
DJANGO_SETTINGS_MODULE = "shift_scheduler.settings.development"  # 開発設定を使用


[functions]
directory = "netlify/functions"

